---
name: Best
version: 0.05
author:
  - 'Gaal Yahas <gaal@forum2.org>'
abstract: Fallbackable module loader
license: perl
build_requires:
  Test::Exception: 0
  Test::More: 0
provides:
  Best:
    file: lib/Best.pm
    version: 0.05
generated_by: Module::Build version 0.26
